# Generated by Django 2.2 on 2019-09-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
